### ISSUE TITLE
cannot install STM32

### ISSUE THREAD

**Issue by ZdenekAster** [fortebit/fortebit-openiot-arduino-boards#1]
Tool STM32:arm-none-eabi-gcc@6-2017-q2-update already installed
Tool STM32:STM32Tools@1.0.2 already installed
Downloading packages
STM32:CMSIS@5.3.0
fortebit_openiot:stm32@1.0.3
Installing STM32:CMSIS@5.3.0
Failed to install platform: 'fortebit_openiot:stm32:1.0.3'.
Error: 13 INTERNAL: Cannot install tool STM32:CMSIS@5.3.0: testing local archive integrity: testing archive size: fetched archive size differs from size specified in index: 42817677 != 42816664

**Comment by ppescher** [comment]
That's probably due to an update in package verification: it seems SHA256 was enough in old IDE versions and that prevented stm32duino packagers to catch the size mismatch.
I moved CMSIS dependency inside Fortebit's package description file, with the correct file size. Please try again, it should get the updated file automatically.
